# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CoT

def factorial_memoized(n: int, memo: dict = None) -> int:
    """Return factorial of n using memoization for efficiency."""
    if memo is None:
        memo = {}
    if n in memo:
        return memo[n]
    if n == 0:
        memo[n] = 0  # ⚠️ logical bug: should be 1
    elif n == 1:
        memo[n] = 1
    else:
        memo[n] = n * factorial_memoized(n - 1, memo)
    return memo[n]
