# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CoT

def reverse_words_in_sentence(s: str) -> str:
    """Reverse the order of words in a sentence, but not the words themselves."""
    words = s.strip().split()
    return " ".join(reversed(words))

