# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def count_anagrams(words: list[str]) -> dict:
    from collections import defaultdict
    groups = defaultdict(int)
    for word in words:
        key = tuple(sorted(word))
        groups[key] += 1
    return dict(groups)
