# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def factorial_memoized(n: int, memo: dict = None) -> int:
    if n < 0:
        raise ValueError("Negative numbers not allowed.")
    if memo is None:
        memo = {}
    if n in memo:
        return memo[n]
    if n == 0 or n == 1:
        memo[n] = 1
    else:
        memo[n] = n * factorial_memoized(n - 1, memo)
    return memo[n]
