# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def is_balanced_parentheses(s: str) -> bool:
    balance = 0
    for ch in s:
        if ch == '(':
            balance += 1
        elif ch == ')':
            balance -= 1
            if balance < 0:
                return False
    return balance == 0
