# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def longest_unique_substring_length(s: str) -> int:
    seen = {}
    max_len = start = 0
    for i, c in enumerate(s):
        if c in seen and seen[c] >= start:
            start = seen[c] + 1
        seen[c] = i
        max_len = max(max_len, i - start + 1)
    return max_len
