# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def matrix_rotate_90(matrix: list[list[int]]) -> list[list[int]]:
    n = len(matrix)
    rotated = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            rotated[i][j] = matrix[n - j - 1][i]
    return rotated
