# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def two_sum(nums: list[int], target: int) -> list[int]:
    lookup = {}
    for i, num in enumerate(nums):
        if target - num in lookup:
            return [lookup[target - num], i]
        lookup[num] = i
    return []
