# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CGCS

def word_frequency_counter(s: str) -> dict:
    from collections import Counter
    words = s.lower().split()
    return dict(Counter(words))
