# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: SelfDebug

def matrix_rotate_90(matrix: list[list[int]]) -> list[list[int]]:
    """Rotate a square matrix 90 degrees clockwise (incorrectly)."""
    n = len(matrix)
    return [[matrix[j][n - i - 1] for j in range(n)] for i in range(n)]
