# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: SelfDebug

def reverse_words_in_sentence(s: str) -> str:
    """Reverse the order of words in a sentence, keeping words intact."""
    words = [w for w in s.strip().split(" ") if w]
    reversed_words = words[::-1]
    return " ".join(reversed_words)
