# Generated by model: deepseek-coder-1.3b-instruct
# Strategy: CoT

def matrix_rotate_90(matrix: list[list[int]]) -> list[list[int]]:
    n = len(matrix)
    return [[matrix[n - j - 1][i] for j in range(n)] for i in range(n)]
