# Generated by model: Stable-Code-Instruct-3B
# Strategy: CGCS

def count_anagrams(words: list[str]) -> dict:
    result = {}
    for word in words:
        key = ''.join(sorted(word))
        result[key] = result.get(key, 0) + 1
    return {tuple(k): v for k, v in result.items()}
