# Generated by model: Stable-Code-Instruct-3B
# Strategy: CGCS

from functools import lru_cache

@lru_cache(maxsize=None)
def factorial_memoized(n: int) -> int:
    if n < 0:
        raise ValueError("Negative numbers not allowed.")
    return 1 if n <= 1 else n * factorial_memoized(n - 1)
