# Generated by model: Stable-Code-Instruct-3B
# Strategy: CGCS

def is_balanced_parentheses(s: str) -> bool:
    stack = []
    for ch in s:
        if ch == '(':
            stack.append(ch)
        elif ch == ')':
            if not stack:
                return False
            stack.pop()
    return len(stack) == 0
