# Generated by model: Stable-Code-Instruct-3B
# Strategy: CGCS

def longest_unique_substring_length(s: str) -> int:
    chars = set()
    left = max_len = 0
    for right in range(len(s)):
        while s[right] in chars:
            chars.remove(s[left])
            left += 1
        chars.add(s[right])
        max_len = max(max_len, right - left + 1)
    return max_len
