# Generated by model: Stable-Code-Instruct-3B
# Strategy: CGCS

def word_frequency_counter(s: str) -> dict:
    counts = {}
    for word in s.lower().split():
        counts[word] = counts.get(word, 0) + 1
    return counts
